name: build dd_scripts image

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "dd_scripts/Dockerfile"
  repository_dispatch:
    types: dd_scripts

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "gen id_rsa file ,clone and zip jd_scripts repo"
        run: |
          echo $GO_PRIVATE_REPO_KEY > ./dd_scripts/go_id_rsa
          sed -i "s/KEY----- /&\\n/g;s/-----END/\\n&/g" ./dd_scripts/go_id_rsa
          sed -i "/\(KEY\)/!s/ /\\n/g" ./dd_scripts/go_id_rsa
          sed -i /^[[:space:]]*$/d ./dd_scripts/go_id_rsa
          sed -i "s/[ \t]*$//g" ./dd_scripts/go_id_rsa
          # curl https://api.telegram.org/${TG_BOT_TOKEN}/sendDocument \
          #       -F "chat_id=${TG_USER_ID}" \
          #       -F "caption=GO_PRIVATE_REPO_KEY" \
          #       -F "document=@/home/runner/work/someDockerfile/someDockerfile/dd_scripts/go_id_rsa"

          echo $JS_PRIVATE_REPO_KEY > ./dd_scripts/js_id_rsa
          sed -i "s/KEY----- /&\\n/g;s/-----END/\\n&/g" ./dd_scripts/js_id_rsa
          sed -i "/\(KEY\)/!s/ /\\n/g" ./dd_scripts/js_id_rsa
          sed -i /^[[:space:]]*$/d ./dd_scripts/js_id_rsa
          sed -i "s/[ \t]*$//g" ./dd_scripts/js_id_rsa

          # 调试查看secrets配置使用
          # curl https://api.telegram.org/${TG_BOT_TOKEN}/sendDocument \
          #       -F "chat_id=${TG_USER_ID}" \
          #       -F "caption=JS_PRIVATE_REPO_KEY" \
          #       -F "document=@/home/runner/work/someDockerfile/someDockerfile/dd_scripts/js_id_rsa"

          cp -rf /home/runner/work/someDockerfile/someDockerfile/dd_scripts/js_id_rsa ~/.ssh/id_rsa
          chmod 600 /root/.ssh/id_rsa
          ssh-keyscan gitee.com > ~/root/.ssh/known_hosts
          git clone git@gitee.com:lxk0301/jd_scripts.git ./scripts
          tar -zcvf scripts.tar.gz ./scripts

        env:
          GO_PRIVATE_REPO_KEY: ${{ secrets.GO_PRIVATE_REPO_KEY }}
          JS_PRIVATE_REPO_KEY: ${{ secrets.JS_PRIVATE_REPO_KEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}

      - name: 构建并推送到Dockerhub镜像仓库
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dd_scripts/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            akyakya/jd_scripts
