name: Build Docker Image CI

on:
  push:
    branches:
      - dev
    paths:
      - 'efb-v2/Dockerfile'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: echo path
         run: echo $path


      - uses: actions/checkout@master
      - name: Build the Docker image
        run: docker build . --file ./efb-v2/Dockerfile --tag akyakya/efb-v2:$(date +%s)
