name: Build efb-v2 Docker Image

on:
  push:
    paths:
      - 'efb-v2/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@master

      - name: 构建镜像
        run: docker build . --file ./efb-v2/Dockerfile --tag akyakya/efb-v2:$(date +%s)

      - name: 推送到Dockerhub官方镜像仓库
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: akyakya/efb-v2
          tag_with_ref: true

      - name: 推送到Github镜像仓库
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: iouAkira/someDockerfile/efb-v2
          tag_with_ref: true