name: Build efb-v2 Docker Image

on:
  push:
    branches:
      - master
    paths:
      - 'efb-v2/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: 构建并推送到Dockerhub官方镜像仓库
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: efb-v2/Dockerfile
          repository: akyakya/efb-v2
          tag_with_ref: true

      - name: 推送到Github镜像仓库
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: iouakira/somedockerfile/efb-v2
          tag_with_ref: true