name: 构建gd-utils Docker镜像

on:
  push:
    branches:
      - master
    paths:
      - 'gd-utils/Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      # - name: 构建并推送到Dockerhub官方镜像仓库
      #   uses: docker/build-push-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     dockerfile: gd-utils/Dockerfile
      #     repository: akyakya/gd-utils
      #     tag_with_ref: true
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: 构建并推送到Github Packages
        uses: docker/build-push-action@master
        with:
          context: .
          file: gd-utils/Dockerfile
          push: true
          tags: iouakira/gd-utils:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ github.token }}